# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5f97bbf912cd0183dbe9b9a47105d0f560cb245acc4cf6ab96c5f9f3bf7036f04d3eba3470b11787111301cf34a82d93e90d5a79d764dd1ce649bbe45b1bb6e

test:
  secret_key_base: 8f2af65370ba5e3d8998aca599b39fe5250b7e23ef9a413a0e22bcf8a1b963ebac4bf5642c9510d518c86f3539e86f592d09fcfe257caeda1848025b6137464f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
